customer:
  property: Bootcoin Profile Dev

server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: bootcoin
  data:
    mongodb:
      uri: mongodb+srv://ecalderc:az9Y7tr5eGTgHzVF@bootcamp.yi8qeh1.mongodb.net/?retryWrites=true&w=majority
      database: dbBC40Wallet

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      customer:
        failureRateThreshold: 50
        minimumNumberOfCalls: 10
        slidingWindowType: TIME_BASED
        slidingWindowSize: 10
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5
  timelimiter:
    instances:
      customer:
        timeout-duration: 2s