server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  data:
    mongodb:
      uri: mongodb+srv://dev:az9Y7tr5eGTgHzVF@nttdata.tipkdvn.mongodb.net/bootcamp?retryWrites=true&w=majority
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/ecalderc/customer-microservice
  application:
    name: customer

eureka:
  instance:
    hostname: host.docker.internal
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka
    prefer-ip-address: true

resilience4j.circuitbreaker:
  instances:
    customer:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 3s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10