customer:
  property: Customer Profile Dev

server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: customer
  data:
    mongodb:
      uri: mongodb+srv://dev:az9Y7tr5eGTgHzVF@nttdata.tipkdvn.mongodb.net/bootcamp?retryWrites=true&w=majority

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    prefer-ip-address: true

resilience4j.circuitbreaker:
  instances:
    customer:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 3s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

spring-doc:
  api-docs:
    enabled: true
    path: /api-docs
swagger-ui:
  path: swagger-ui-custom.html