server:
  port: 9000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    prefer-ip-address: true
    
spring:
  application:
    name: gateway
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/ecalderc/gateway
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer
          uri: lb://customer
          predicates:
            - Path=/customer/**
        - id: movement
          uri: lb://movement
          predicates:
            - Path=/movement/**
        - id: currentAccount
          uri: lb://passive
          predicates:
            - Path=/currentAccount/**
        - id: savingAccount
          uri: lb://passive
          predicates:
            - Path=/savingAccount/**
        - id: fixedTerm
          uri: lb://passive
          predicates:
            - Path=/fixedTerm/**
        - id: credit
          uri: lb://credit
          predicates:
            - Path=/credits/**
        - id: statusaccount
          uri: lb://statusaccount
          predicates:
            - Path=/status/**