server:
  port: 9000

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    prefer-ip-address: true
    
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer
          uri: lb://customer
          predicates:
            - Path=/customer/**
        - id: movement
          uri: lb://movement
          predicates:
            - Path=/movement/**
        - id: currentAccount
          uri: lb://currentAccount
          predicates:
            - Path=/currentAccount/**
        - id: credit
          uri: lb://credit
          predicates:
            - Path=/credits/**
        - id: statusaccount
          uri: lb://statusaccount
          predicates:
            - Path=/status/**