server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: movement
  data:
    mongodb:
      uri: mongodb+srv://ecalderc:az9Y7tr5eGTgHzVF@bootcamp.yi8qeh1.mongodb.net/?retryWrites=true&w=majority
      database: dbBC40Movement

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    prefer-ip-address: true

resilience4j.circuitbreaker:
  instances:
    movement:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 3s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10