server:
  port: 9000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://eureka-server-ecalderc.azurewebsites.net/eureka
    prefer-ip-address: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: gateway
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer
          uri: lb://customer
          predicates:
            - Path=/customer/**
        - id: movement
          uri: lb://movement
          predicates:
            - Path=/movement/**
        - id: currentAccount
          uri: lb://passive
          predicates:
            - Path=/currentAccount/**
        - id: savingAccount
          uri: lb://passive
          predicates:
            - Path=/savingAccount/**
        - id: fixedTerm
          uri: lb://passive
          predicates:
            - Path=/fixedTerm/**
        - id: credit
          uri: lb://credit
          predicates:
            - Path=/credits/**
        - id: statusaccount
          uri: lb://statusaccount
          predicates:
            - Path=/status/**